### ISSUE TITLE
Get information about files in folders

### ISSUE THREAD

**Issue by gauda** [keep2share/api#3]
Hallo,

great API but I am missing a method to get all files of a folder. Can you add something like that?

Thank you!

**Comment by keep2share** [comment]
Hi,
you can use method `getFilesList` 
for get files in folder, you need specify first parameter `parent` (must be an folder id)

**Comment by gauda** [comment]
But this way you can only get files of your own folders, right? There is no way to get files of public folders?

**Comment by keep2share** [comment]
hm, ok, we add it in the near future

**Comment by keep2share** [comment]
Access to public folders by `getFilesList` now allowed for all
