### ISSUE TITLE
Not possible to use api in scripts! Remove Captcha!

### ISSUE THREAD

**Issue by n0v3xx** [keep2share/api#7]
Hey, you publish an API where its not possible to use that in an automatic running script. I must enter a captcha verification in an API request?! Nobody implement that in an API !

API use normaly tokens or credentials and no captcha!
The script run on a cli and its not possible to enter a captcha code ...

Please remove this from the login requests otherwise your complete API make no sense. Its not possible to use it in an script.

**Comment by keep2share** [comment]
You can use `access_token`s mechanism instead of username/password pair.
See example here https://github.com/keep2share/api/blob/master/exampleAPI.php#L13
