### ISSUE TITLE
Wrong signature.

### ISSUE THREAD

**Issue by axago** [keep2share/api#9]
hi, well, no matter what, i got this error at the end of upload
{
    "name": "Bad Request",
    "message": "Wrong signature. IP XX.XX.XX.XX",
    "code": 0,
    "status": 400
}

i already getuploadforDama , but can't upload file correctly

{
    "status": "success",
    "code": 200,
    "form_action": "https://file-api-31.keep2share.cc:8443/upload",
    "file_field": "file",
    "form_data": {
        "ajax": true,
        "params": "{\"project\":\"moneyplatform\",\"expire\":1572511732,\"extras\":{\"user_id\":xxxxx,\"parent_id\":\"\\/\",\"project_name\":\"k2s\",\"create_method\":10}}",
        "signature": "e8fe4c9e15488cba9bb..........b18d5f00e4d20ec1"
    }
}

**Comment by q932** [comment]
I am getting the exact same error.  Did you eventually get this right?

Can any of the devs explain why they cant update the example https://github.com/keep2share/api/blob/master/uploadFile.sh in the repo??
Your script is extremely old and its not helping new users, only confusing them.  The API explanation on your site is even worse at explaining.

This is the simple example bash script i have:
```
#!/bin/bash

Token="XXXXXXXXXX"

cmd=$(curl -s -H 'Content-Type: application/json' -d '{"access_token": "'"${Token}"'"}' "https://keep2share.cc/api/v2/getUploadFormData" | jq -r .)

FullFileName="/home/user/Folder/Test.txt"
Form_Action=$(echo "$cmd" | jq -r ".form_action")
FileField=$(echo "$cmd" | jq -r ".file_field")
Ajax=$(echo "$cmd" | jq -r ".form_data.ajax")
Project=$(echo "$cmd" | jq -r ".form_data.params" | jq -r ".project")
Expire=$(echo "$cmd" | jq -r ".form_data.params" | jq -r ".expire")
UserID=$(echo "$cmd" | jq -r ".form_data.params" | jq -r ".extras.user_id")
ParentID=$(echo "$cmd" | jq -r ".form_data.params" | jq -r ".extras.parent_id")
ProjectName=$(echo "$cmd" | jq -r ".form_data.params" | jq -r ".extras.project_name")
CreateMethod=$(echo "$cmd" | jq -r ".form_data.params" | jq -r ".extras.create_method")
Sig=$(echo "$cmd" | jq -r ".form_data.signature")


cmd2=$(curl -v -F "file=@$FullFileName" -F "ajax=$Ajax" -F "project=$Project" -F "expire=$Expire" -F "user_id=$UserID" -F "parent_id=$ParentID" -F "project_name=$ProjectName" -F "create_method=$CreateMethod" -F "signature=$Sig" "$Form_Action")
 
echo "$cmd2"
```

There is something crucial i am missing in the last command because it keeps giving error: 

`message": "Wrong signature. IP XX.XX.XX.XX"`

Please can someone help??

**Comment by keep2share** [comment]
Hello!
To upload file via CURL you can use the next script:

```bash
#!/bin/bash

Token="XXXXXXXX"

cmd=$(curl -s -H 'Content-Type: application/json' -d '{"access_token": "'"${Token}"'"}' "https://keep2share.cc/api/v2/getUploadFormData" | jq -r .)
echo "$cmd"

FullFileName="/Users/username/Test.txt"
Form_Action=$(echo "$cmd" | jq -r ".form_action")
FileField=$(echo "$cmd" | jq -r ".file_field")
Ajax=$(echo "$cmd" | jq -r ".form_data.ajax")
Params=$(echo "$cmd" | jq -r ".form_data.params")
Sig=$(echo "$cmd" | jq -r ".form_data.signature")

cmd2=$(curl -F "$FileField=@$FullFileName" -F "ajax=$Ajax" -F "signature=$Sig" -F "params=$Params" "$Form_Action")
```
As you can see you do not need to send every parameter separately. You need to get Params from a response and send it to us as-is.
